// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	BUCKET_OWNER_ACCOUNT_ID: string;
	BUCKET_NAME: string;
	CLOUDFLARE_API_TOKEN: string;
	SLACK_BOT_TOKEN: string;
	SLACK_POST_CHANNEL_ID: string;
}
