name = "crescent-asset-size-reporter"
main = "index.ts"
compatibility_date = "2024-11-29"
workers_dev = false
preview_urls = false

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
# JSTで朝4時に来てほしい
crons = ["0 19 * * *"]
